# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-01 10:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_auto_20190330_2242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donateorderlineitem',
            name='donate',
        ),
        migrations.RemoveField(
            model_name='donateorderlineitem',
            name='order',
        ),
        migrations.DeleteModel(
            name='DonateOrder',
        ),
        migrations.DeleteModel(
            name='DonateOrderLineItem',
        ),
    ]
