# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-01 12:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('volo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='volo',
            name='status',
            field=models.CharField(choices=[('received', 'Received'), ('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default=django.utils.timezone.now, max_length=40),
            preserve_default=False,
        ),
    ]
